apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-pipe
  name: hello-pipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-pipe
  template:
    metadata:
      labels:
        app: hello-pipe
    spec:
      containers:
        - image: quay.io/openshift-pipeline/vote-api:latest
          imagePullPolicy: Always
          name: hello-pipe
          ports:
            - containerPort: 9000
              protocol: TCP
